# netlify.toml

[build]
publish = "dist/"
command = "npm run build"
[build.processing]
skip_processing = false
[build.processing.css]
bundle = true
minify = true
[build.processing.js]
bundle = true
minify = true
[build.processing.html]
pretty_urls = true
[build.processing.images]
compress = true

[[redirects]]
from = "/listening"
to = "https://listenbrainz.org/user/BinyaminG"

[[redirects]]
from = "/profile.jpeg"
to = "/assets/img/profile/profile.jpeg"

## Blog redirects

[[redirects]]
from = "/c/blog"
to = "/p"

[[redirects]]
from = "/c/micro"
to = "/p"

[[redirects]]
from = "/feeds/all.json"
to = "/p/feed.json"

[[redirects]]
from = "/feeds/all.xml"
to = "/p/feed.xml"

[[headers]]
for = "/**/*"
[headers.values]
cache-control = '''max-age=31536000'''
X-Content-Type-Options = "nosniff"
Permissions-Policy = "interest-cohort=()"
